In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8] #valor do index 8 / posicao 9

8

In [5]:
arr[1:5] #valor do index 1 a 5 / posicoes 2 a 5

array([1, 2, 3, 4])

In [6]:
arr[:6] #valor desde o inicio do array ate index 6

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:] #valor desde o index 5 até ao fim

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100 #atribui até ao index 5, o valor 100

In [9]:
arr = np.arange(0,11) #voltamos aos valores iniciais

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr #criacao de um array com valores do nosso array

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr #o array inicial, toma o valor do slice. para evitar isto, temos 
#de criar uma copia do nosso array inicial

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [22]:
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr #neste caso vemos que o array permaneceu sem mudanças

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
# ----------------------- MATRIZES ---------------------

In [27]:
arr_2d = np.array([[5,10,15], [20,25,30], [35, 40, 45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[0][0] #valor da primeira linha da primeira coluna

5

In [30]:
arr_2d[0] #valores da primeira linha

array([ 5, 10, 15])

In [32]:
arr_2d[2][1] #para encontrar o 40

40

In [33]:
arr_2d[2,1] #exatamente a mesma coisa (e mais simples)

40

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[1:3,0:] #a primeira parte é: todas as linhas desde o index 1 à 3
# a segunda: dentro dessas linhas, alberga os valores do index 0 ate ao fim

array([[20, 25, 30],
       [35, 40, 45]])

In [39]:
arr = np.arange(1,11)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
bool_arr = arr > 5

In [43]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
 arr[bool_arr] #so apresenta os valores true

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr>5] #mesma coisa (vamos usar esta versao)

array([ 6,  7,  8,  9, 10])

In [47]:
arr[arr<3]

array([1, 2])

In [48]:
arr_2d = np.arange(50).reshape(5,10)

In [49]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[2:4,2:5] #o limite tem de ser a linha seguinte à que pretendemos

array([[22, 23, 24],
       [32, 33, 34]])