In [1]:
#array with array
#array with scalars
#universal array functions

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr + arr #soma os valores de cada array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr * arr #cada valor de cada index multiplica pelo mesmo index do outro array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr + 100 #adiciona 100 a cada valor do array (= para outras op)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [8]:
arr / arr #0 a dividir por 0 é indefinido -> nan (da um aviso, nao um erro)

C:\Users\Carlos\AppData\Local\Temp\ipykernel_7872\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / arr #divide 1 por cada valor do array (1/0 tmb da erro)

C:\Users\Carlos\AppData\Local\Temp\ipykernel_7872\3177181013.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr #divide 1 por cada valor do array (1/0 tmb da erro)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [12]:
np.sqrt(arr) #quadrado de cada valor do array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
np.exp(arr) 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [14]:
np.max(arr) # é = a arr.max()

10

In [15]:
np.sin(arr) #converte cada valor em seno

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.sin(cos) #converte cada valor em coseno