In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] #o segundo par de parentesis reto é para indicar que é uma matriz

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2) #cria um array de 0 a 10, (o terceiro argumento significa de 2 em 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4)) #2 dimensoes, mas com 3 linhas

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,100) #criacao de 100 pontos no array entre 0 e 5

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [14]:
np.eye(4) #identity matrix. nº de linhas = colunas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5) #cria um array com 5 amostras de 0 a 1, de uma dimensao (uma tupla)
#estes valores de 0 a 1, remetem para uma distribuição uniforme

array([0.36916873, 0.07649283, 0.90176344, 0.46730205, 0.85150724])

In [16]:
np.random.rand(5,5) #array de 2 dimensoes com 5 colunas/linhas

array([[0.90428359, 0.12583755, 0.55307016, 0.44750223, 0.51588916],
       [0.33065381, 0.35062505, 0.13587466, 0.36682401, 0.77508473],
       [0.26946461, 0.51397418, 0.92515907, 0.928961  , 0.3439474 ],
       [0.44796102, 0.81959945, 0.99597128, 0.07491077, 0.962553  ],
       [0.65471415, 0.00684752, 0.16108747, 0.15410394, 0.75762572]])

In [17]:
np.random.randn(2) #aqui sim é uma distribuição normal (ou curva gaussiana)
#podia novamente colocar outro valor para aumentar as colunas/linhas e torna-la 2D

array([-0.64928627, -0.08700245])

In [18]:
np.random.randint(1,100, 10) # 10 inteiros random entre 1 e 100 (100 n incluido)

array([88, 52, 76, 56, 93,  1, 25, 28, 71, 36])

In [19]:
arr = np.arange(25)#array de 0 a 24

In [20]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr = np.random.randint(0,50,10)

In [22]:
ranarr

array([ 3, 13, 18, 35, 33, 46,  7, 24,  5, 33])

In [24]:
arr.reshape(5,5) #muda a estrutura do array para 2D. no caso do arr como tinhamos
#25 numeros, deu resultado porque temos 5x5 colunas/linhas. Caso nao tivessemos
#dava erro. nº valores do array tem de ser = valor da estrutura

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max() #valor max do array

46

In [26]:
ranarr.min() #valor min do array

3

In [27]:
ranarr.argmax() #o valor max esta na posicao 5 do index

5

In [28]:
ranarr.argmin()

0

In [29]:
arr.shape #o resultado significa que tem 25 valores, numa so dimensao
#se eu mudar a estrutura, pex: 5,5 o shape tmb fica 5,5

(25,)

In [30]:
arr.dtype #tipo do array

dtype('int32')

In [31]:
from numpy.random import randint 

In [32]:
randint(2,10) # substitui a linha 18

7